# TelemacFile

TelemacFile is a class over HermesFile (low-level Python class for the Hermes I/O module).

You can have a look at the notebook on [HermesFile](../../telapy/hermes.ipynb) for more information.

This class is more user friendly as it gives easier access to data from a file.

It has the same preresuisites as HermesFile (The hermes api must be compiled).

In [1]:
from data_manip.extraction.telemac_file import TelemacFile

help(TelemacFile)

Help on class TelemacFile in module data_manip.extraction.telemac_file:

class TelemacFile(telapy.api.hermes.HermesFile)
 |  Class to extract data from a TelemacFile
 |  
 |  Method resolution order:
 |      TelemacFile
 |      telapy.api.hermes.HermesFile
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, file_name, bnd_file=None, log_lvl='INFO', fformat=None, access='r')
 |      Initialisation of a file reader
 |      
 |      @param file_name (str) Name of the mesh file
 |      @param bnd_file (str) Name of the boundary file (default None)
 |      @parma log_lvl (str) Level of log information
 |  
 |  discretize_polyline(self, polyline)
 |      Will return the number of point for each polyline segment taking the
 |      minimum mesh resolution as step
 |      
 |      @param polyline (list) List of points of the polyline
 |      
 |      @returns (list) List of discretisation for each segment
 |  
 |  get_angular_dispersion(self, point, record, radian=Fal

# Intialising the class

The format will be identify by the extension:
  * .med -> MED format
  * anything else SERAFIN format

To write a double precision SERAFIN you will need to specify the format with the additional keyword fformat.

You should always close the file at the end.

In [2]:
from os import path, environ
import numpy as np

file_name = path.join(environ['HOMETEL'], 'notebooks', 'data', 'r2d_bridge.slf')
res = TelemacFile(file_name)

print(res)

res.close()

********************************
Generic info
********************************
Title: ELEMAC 2D : TEST PONT                                                  
Date: 1/1/1900 0H0M0S
********************************
Mesh info
********************************
Ndim: 2
Element type: TRIANGLE
Npoin: 2900
Nelem: 5550
Ndp: 3
nplan: 0
coordinates:
 - On x :[  5.   5.   5. ... 515. 515. 515.]
 - On y :[ 0. 10. 20. ... 20. 10.  0.]
ikle: [[   0   38    1]
 [   1   38   29]
 [   1   29    2]
 ...
 [2897 2898 1214]
 [2898 1213 1214]
 [2898 2899 1213]]
********************************
Parallel info
********************************
No parallel information
********************************
Bnd info
********************************
No boundary information********************************
Data info
********************************
ntimestep: 37
nvar: 5
var info:
('VELOCITY U', 'M/S')
('VELOCITY V', 'M/S')
('FREE SURFACE', 'M')
('BOTTOM', 'M')
('Traceur1', '')
Time: 0.000000s
 - for VELOCITY U:
     [0. 0. 

## What you have access to

Here is a quick overview of the kind of function you have access to:
- variable of the file such as the coordinaties, the connectivy table...
- data information: value of a field at a given record, list of variables,  number of time steps...
- Boundary information (if you gave the boundary file)
- Extraction functions: extraction on a polyline, on a point... (you can see more about those in the other notebooks on extraction)

## Variables

Most of the mesh variables are available for 2d and 3d.
If the mesh is 2d they are the same.

For example the script below extract a couple information on the mesh.

In [3]:
file_name = path.join(environ['HOMETEL'], 'notebooks', 'data', 'r2d_bridge.slf')
bnd_file = path.join(environ['HOMETEL'], 'notebooks', 'data', 'geo_bridge.cli')

In [4]:
res = TelemacFile(file_name)

print("Title: ", res.title)
print("Number of 3d points: ", res.npoin3)
print("Number of 2d points: ", res.npoin2)
print("Coordinates x info: min={}, max={}".format(np.min(res.meshx), np.max(res.meshx)))
print("Coordinates y info: min={}, max={}".format(np.min(res.meshy), np.max(res.meshy)))
print("Number of element 3d elements: ", res.nelem3)
print("Number of element 2d elements: ", res.nelem2)

#Closing the file
res.close()

Title:  TELEMAC 2D : TEST PONT                                                  SERAFIN 
Number of 3d points:  2900
Number of 2d points:  2900
Coordinates x info: min=5.0, max=995.0
Coordinates y info: min=0.0, max=250.0
Number of element 3d elements:  5550
Number of element 2d elements:  5550


## data information

In [5]:
res = TelemacFile(file_name)

print("Number of records: ", res.ntimestep)
print("Number of variables: ", res.nvar)
print("Variable names: ", res.varnames)
print("Variable units: ", res.varunits)
print("Times for each record: ", res.times)
print("Bottom at record 12 (time {}s): {}".format(res.times[12], res.get_data_value("BOTTOM", 12)))

res.close()

Number of records:  37
Number of variables:  5
Variable names:  ['VELOCITY U', 'VELOCITY V', 'FREE SURFACE', 'BOTTOM', 'Traceur1']
Variable units:  ['M/S', 'M/S', 'M', 'M', '']
Times for each record:  [   0.  200.  400.  600.  800. 1000. 1200. 1400. 1600. 1800. 2000. 2200.
 2400. 2600. 2800. 3000. 3200. 3400. 3600. 3800. 4000. 4200. 4400. 4600.
 4800. 5000. 5200. 5400. 5600. 5800. 6000. 6200. 6400. 6600. 6800. 7000.
 7200.]
Bottom at record 12 (time 2400.0s): [9.99995041 9.49995518 8.99995995 ... 9.6373539  9.68735123 9.73734856]


## Boundary information

They are contained in the variable bnd_info which contains the arrays (lihbor, liubor...).
The full detail of the content can be found in the documentation of get_bnd_value.
We need to open the file with the boundary file.

In [6]:
res = TelemacFile(file_name, bnd_file=bnd_file)

help(res.get_bnd_value)
print("Boundary arrays: ", res.bnd_info)

res.close()

Help on method get_bnd_value in module telapy.api.hermes:

get_bnd_value() method of data_manip.extraction.telemac_file.TelemacFile instance
    Retuns the information on the boundary values
    
    @returns liubor, lihbor, livbor, hbor, ubor, vbor, chbord,
             litbor, tbor, atbor, btbor

Boundary arrays:  (array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2,

# Modification of a file

You have to possibility to read/load the data from a TelemacFile into another TelemacFile (That can be the same).
This means that all the variable mentionned before will be read from the file.
You can then modify them however you want.
And you can then call a function to write the content of the class variables back into the file.

If you add the boundary file in your TelemacFile boundary data will be transferred as well.

Here are a couple example of some actions you can do.

## Adding a variable to a file

When adding a new variable you need to update:
- The list of variable names and units
- Increase the number of variable
- Add the values for that variable for each record

Here I will add a bogus variable which contains only ones.

In [7]:
%%bash
cp $HOMETEL/notebooks/data/r2d_bridge.slf $HOMETEL/notebooks/data/r2d_bridge1.slf

In [8]:
print("Adding new variable in {}".format(file_name))
file_name = path.join(environ['HOMETEL'], 'notebooks', 'data', 'r2d_bridge1.slf')

res = TelemacFile(file_name, access='rw')

# Loading data from file
res.read(res)

# Adding new variable
res._varnames.append('stuff')
res._varunits.append('M')
res._nvar += 1

bathy = np.ones((res.ntimestep, 1, res.npoin3), dtype=np.float64)

res._values = np.append(res._values, bathy, axis=1)

# Writting class data
res.write()

res.close()

Adding new variable in /home/B61570/opentelemac/git/trunk/notebooks/data/r2d_bridge.slf


In [9]:
%%bash
cd $HOMETEL/notebooks/data

run_selafin.py scan --core r2d_bridge.slf > init.log

run_selafin.py scan --core r2d_bridge1.slf > modif.log

colordiff init.log modif.log

echo

8c8
< Scanning r2d_bridge.slf within /home/B61570/opentelemac/git/trunk/notebooks/data
---
> Scanning r2d_bridge1.slf within /home/B61570/opentelemac/git/trunk/notebooks/data
21a22
>    - stuff           M               
24c25
<    - nptfr* = 248
---
>    - nptfr* = 0
39c40
<    - ipobo  : / min: [ 0 ]  / max: [ 248 ] [  1 248 247 ...   0   0  52]
---
>    - ipobo  : / min: [ 0 ]  / max: [ 0 ] [0 0 0 ... 0 0 0]
229a231,268
> Variable     : stuff           
>     / Time: 0.0 / min: 1.0 / max: 1.0
>     / Time: 200.0 / min: 1.0 / max: 1.0
>     / Time: 400.0 / min: 1.0 / max: 1.0
>     / Time: 600.0 / min: 1.0 / max: 1.0
>     / Time: 800.0 / min: 1.0 / max: 1.0
>     / Time: 1000.0 / min: 1.0 / max: 1.0
>     / Time: 1200.0 / min: 1.0 / max: 1.0
>     / Time: 1400.0 / min: 1.0 / max: 1.0
>     / Time: 1600.0 / min: 1.0 / max: 1.0
>     / Time: 1800.0 / min: 1.0 / max: 1.0
>     / Time: 2000.0 / min: 1.0 / max: 1.0
>     / Time: 2200.0 / min: 1.0 / max: 1.0
>     / Time: 2400.0 / min: 1.

We can see that the information on the boundary conditions were lost as we did not give the boundary condition file.

## Adding a new record to a file

When adding a new record you need to update:
- The list of times
- Increase the number of records
- Add the values for that record for each variables

Here I will add a bogus record which contains only ones.

In [10]:
%%bash
cp $HOMETEL/notebooks/data/r2d_bridge.slf $HOMETEL/notebooks/data/r2d_bridge1.slf

In [11]:
print("Adding new record in {}".format(file_name))
res = TelemacFile(file_name, access='rw')

res.read(res)

res._times = np.append(res._times, [666.0], axis=0)
res._ntimestep += 1

bathy = np.ones((1, res._nvar, res.npoin3), dtype=np.float64)

res._values = np.append(res._values, bathy, axis=0)

res.write()

res.close()

Adding new record in /home/B61570/opentelemac/git/trunk/notebooks/data/r2d_bridge1.slf


In [12]:
%%bash
cd $HOMETEL/notebooks/data

run_selafin.py scan --core r2d_bridge.slf > init.log

run_selafin.py scan --core r2d_bridge1.slf > modif.log

colordiff init.log modif.log

echo

8c8
< Scanning r2d_bridge.slf within /home/B61570/opentelemac/git/trunk/notebooks/data
---
> Scanning r2d_bridge1.slf within /home/B61570/opentelemac/git/trunk/notebooks/data
24c24
<    - nptfr* = 248
---
>    - nptfr* = 0
39c39
<    - ipobo  : / min: [ 0 ]  / max: [ 248 ] [  1 248 247 ...   0   0  52]
---
>    - ipobo  : / min: [ 0 ]  / max: [ 0 ] [0 0 0 ... 0 0 0]
77a78
>     / Time: 666.0 / min: 1.0 / max: 1.0
115a117
>     / Time: 666.0 / min: 1.0 / max: 1.0
153a156
>     / Time: 666.0 / min: 1.0 / max: 1.0
191a195
>     / Time: 666.0 / min: 1.0 / max: 1.0
229a234
>     / Time: 666.0 / min: 1.0 / max: 1.0

